modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="disablechat"
version="1.0.0"
displayName="Disablechat"
displayURL="https://stabosa.fun"
credits="Ur mom"
authors="stabosa"
# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.disablechat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"



